name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - darwin
          - linux
          - windows
        goarch:
          - amd64
          - arm
          - arm64
    services:
      clickhouse:
        image: yandex/clickhouse-server

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v -o telegraf-clickhouse-plugin cmd/main.go
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      if: ${{ (matrix.goarch == 'amd64') || (matrix.goos == 'linux') }}

    - name: Test
      run: go test -v ./...

